config/routes.rb
Rails.application.routes.draw do
  resources :tickets do
    member do
      put :do_return
      put :undo_return
      delete :submit_return
    end
    collection do
      get :to_return
    end
  end
  resources :users do
    member do
      post :add_money
      put :add_money
      put :sub_money
    end
  end
  root :to => "application#index"
  resources :events do
  end

  get 'session/login'
  get 'session/logout'
  post 'session/login_attempt'
  get 'users/tickets'

end

app/models/event.rb
class Event < ApplicationRecord
  has_many :tickets, dependent: :destroy
  validates_presence_of :name, :description, :price, :date, :image, :size, :message => "nie może pozostać puste"
  validate :event_date_cannot_be_in_the_past
  validates_numericality_of  :size, :price, :greater_than => 0, :message => "musi być większa od zera"

  def event_date_cannot_be_in_the_past
    errors.add(:date, "nie może być z przeszłości") if
        !date.blank? and date < Date.today
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    if params[:commit] == "Filtruj"
      if params[:start_date] != "" && params[:end_date] != "" && params[:start_date] > params[:end_date]
        flash[:danger] = "Data końcowa musi być późniejsza niż początkowa"
        @events = Event.all
      elsif params[:start_date] == ""
        if !session[:admin]
          @events = Event.where(:date => Date.today().to_s..params[:end_date])
        else
          @events = Event.where("date <= ?", params[:end_date].to_date)
        end
      elsif params[:end_date] == ""
        if params[:start_date].to_date < Date.today() && !session[:admin]
          @events = Event.where("date >= ?", Date.today())
        else
          @events = Event.where("date >= ?", params[:start_date].to_date)
        end
      else
        if session[:admin]
          @events = Event.where(:date => params[:start_date]..params[:end_date])
        else
          if params[:start_date].to_date < Date.today
            @events = Event.where(:date => Date.today().to_s..params[:end_date])
          else
            @events = Event.where(:date => params[:start_date]..params[:end_date])
          end
        end
      end
    elsif session[:admin]
      @events = Event.all
    else
      @events = Event.where("date >= ?", Date.today)
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        flash[:success] = "Dodano nowe wydarzenie"
        format.html { redirect_to @event }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        flash[:success] = "Edycja zakończona powodzeniem"
        format.html { redirect_to @event }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      flash[:success] = "Usunięto wydarzenie"
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :price, :date, :adult_only, :image, :size)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="card" style="width: 80%; margin: auto">
  <div class="card-body">
    <h5 class="card-title">Edycja wydarzenia:</h5>
    <hr>
    <%= form_with(model: event, local: true) do |form| %>
      <% if event.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

          <ul>
          <% event.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group row">
        <div class="col-lg-2">
          <%= form.label :Nazwa %><br>
        </div>
        <div class="col-lg-10">
          <%= form.text_field :name, class: "form-control" %>
          <% if !@event.errors.full_messages_for(:name).blank? %>
            <div class="alert alert-danger">
              <%= @event.errors.full_messages_for(:name).first %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-lg-2">
          <%= form.label :Opis %><br>
        </div>
        <div class="col-lg-10">
          <%= form.text_area :description, class: "form-control" %>
          <% if !@event.errors.full_messages_for(:description).blank? %>
            <div class="alert alert-danger">
              <%= @event.errors.full_messages_for(:description).first %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-lg-2">
          <%= form.label :'Cena biletu' %><br>
        </div>
        <div class="col-lg-10">
          <%= form.number_field :price, class: "form-control" %>
          <% if !@event.errors.full_messages_for(:price).blank? %>
            <div class="alert alert-danger">
              <%= @event.errors.full_messages_for(:price).first %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-lg-2">
          <%= form.label :Data %><br>
        </div>
        <div class="col-lg-10">
          <%= form.date_field :date, class: "form-control" %>
          <% if !@event.errors.full_messages_for(:date).blank? %>
            <div class="alert alert-danger">
              <%= @event.errors.full_messages_for(:date).first %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-lg-2">
          <%= form.label :'Ilość miejsc' %><br>
        </div>
        <div class="col-lg-10">
          <%= form.number_field :size, class: "form-control" %>
          <% if !@event.errors.full_messages_for(:size).blank? %>
            <div class="alert alert-danger">
              <%= @event.errors.full_messages_for(:size).first %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-lg-2">
          <%= form.label :'Tylko dla dorosłych' %><br>
        </div>
        <div class="col-lg-10">
          <%= form.check_box :adult_only %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-lg-2">
          <%= form.label :Zdjęcie %><br>
        </div>
        <div class="col-lg-10">
          <%= form.text_field :image, class: "form-control" %>
          <% if !@event.errors.full_messages_for(:image).blank? %>
            <div class="alert alert-danger">
              <%= @event.errors.full_messages_for(:image).first %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="actions">
        <%= form.submit class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/_new_ticket.html.erb
<div class="card" style="width: 100%;">
  <div class="card-body">
    <h5 class="card-title">Wpisz ile biletów chcesz kupic (maksymalnie 5):</h5>
    <hr>

    <%= form_with scope: :ticket, url: tickets_path, local: true do |form| %>

      <div class="form-group row">
        <div class="col-lg-2">
          <%= form.label :'Ilość biletów:' %><br>
        </div>
        <div class="col-lg-10">
          <%= form.text_field :amount, class: "form-control" %>
        </div>
      </div>

      <%= form.hidden_field :price, value: event.price %>
      <%= form.hidden_field :to_return, value: 0.0 %>
      <%= form.hidden_field :user_id, value: user_id %>
      <%= form.hidden_field :event_id, value: event.id %>
      <p>
        <% if session[:user_id] %>
          <%= form.submit :Kup, class: "btn btn-success" %>
        <% else %>
          <%= link_to 'Kup', session_login_path(:danger => "Kup"), class: "btn btn-success" %>
      <% end %>
      </p>
    <% end %>
  </div>
</div>

app/views/events/_tickets_list.html.erb
<p id="notice"><%= notice %></p>

<div style="width: 80%; margin: auto; background-color: white; border-radius: 5px;">
  <h5>Zakupione bilety:</h5>
  <hr>

  <table class="table table-bordered">

    <thead>

    <tr>
      <th>Cena</th>
      <th>Status</th>
      <th>Użytkownik</th>
    </tr>
    </thead>

    <tbody>
    <% tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.price %></td>
        <td>
          <% if ticket.to_return > 0.0 %>
            czeka na zwrot
          <% else %>
            zakupiony
          <% end %>
        </td>
        <td>
          <%= ticket.user.name %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/events/edit.html.erb
<%= render 'form', event: @event %>

app/views/events/index.html.erb
<div class="container">
  <h5>Lista nadchodzących wydarzeń:</h5>
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>" style="margin: auto; margin-bottom: 5px">
      <%= value %>
    </div>
  <% end %>

  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Filtrowanie po dacie</h5>
      <hr>

      <%= form_tag(events_path, :method => :get) do%>
        <div class="form-group" style="display: inline-block;">
          <div class="col-lg-4">
            <%= date_field_tag :start_date, class: "form-control" %>
          </div>
        </div>

        <div class="form-group" style="display: inline-block;">

          <div class="col-lg-4">
            <%= date_field_tag :end_date, class: "form-control" %>
          </div>
        </div>
        <p class="form-group" style="display: inline-block;">
          <%= submit_tag("Filtruj", :class => "btn btn-success") %>
        </p>

      <% end %>
    </div>
  </div>

  <% @events.each do |event| %>
    <div class="card" style="margin-top: 10px;">
      <h5 class="card-header">
        <%= event.name %>
      </h5>
      <div class="card-body">
        <p class="card-text">
        <div class="row">
          <div class="col-lg-4">
            <img src=<%= "#{event.image}" %> alt="" style="max-height: 300px; max-width: 300px;">
          </div>
          <div class="col-lg-8">
            <table class="table">
              <tbody>
              <tr>
                <td>Opis:</td>
                <td><%= event.description %></td>
              </tr>
              <tr>
                <td>Data:</td>
                <td><%= event.date %></td>
              </tr>
              <tr>
                <td>Cena biletu:</td>
                <% if(event.date - Date.today == 0) %>
                  <td><%= event.price.to_f * 1.2 %></td>
                <% else %>
                  <td><%= event.price %></td>
              <% end %>
              </tr>
              <tr>
                <td>Ilość miejsc</td>
                <td><%= event.size %></td>
              </tr>
              <tr>
                <td>Ilość wolnych miejsc</td>
                <td><%= event.size - event.tickets.count %></td>
              </tr>
              <tr>
                <td>Tylko dla pełnoletnich</td>
                <td>
                  <% if(event.adult_only) %>
                    <%= "tak" %>
                  <% else %>
                    <%= "nie" %>
                  <% end %>
                </td>
              </tr>
              </tbody>
            </table>
          </div>
        </div>
        <div style="text-align: right; width: 100%">
          <div class="row">
            <div class="col-lg-12" style="text-align: left">
              <%= link_to 'Szczegóły', event_path(event), class:"btn btn-primary", style: "display: inline-block; float: right" %>
              <% if session[:admin] == true %>
                <p>
                  <%= button_to "Usuń wydarzenie", event, :method=>:delete, class: "btn btn-danger", style: "display: inline-block" %>
                </p>
                <p>
                  <%= link_to "Edytuj", edit_event_path(event), class:"btn btn-primary", style: "display: inline-block" %>
                </p>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-lg-12" style="margin-top: 50px;">
          <% if event.date - Date.today <= 30 && event.date - Date.today >= 0 %>
              <%= render "events/new_ticket", :event => event, :user_id=>session[:user_id] %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/events/new.html.erb
<div class="card" style="width: 80%; margin: auto">
  <div class="card-body">
    <h5 class="card-title">W celu utworzenia wydarzenia, wypełnij poniższy formularz:</h5>
    <hr>

    <%= form_with scope: :event, url: events_path, local: true do |form| %>

      <div class="form-group row">
        <div class="col-lg-2">
          <%= form.label :Nazwa %><br>
        </div>
        <div class="col-lg-10">
          <%= form.text_field :name, class: "form-control" %>
          <% if !@event.errors.full_messages_for(:name).blank? %>
            <div class="alert alert-danger">
              <%= @event.errors.full_messages_for(:name).first %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-lg-2">
          <%= form.label :Opis %><br>
        </div>
        <div class="col-lg-10">
          <%= form.text_area :description, class: "form-control" %>
          <% if !@event.errors.full_messages_for(:description).blank? %>
            <div class="alert alert-danger">
              <%= @event.errors.full_messages_for(:description).first %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-lg-2">
          <%= form.label :'Cena biletu' %><br>
        </div>
        <div class="col-lg-10">
          <%= form.number_field :price, class: "form-control" %>
          <% if !@event.errors.full_messages_for(:price).blank? %>
            <div class="alert alert-danger">
              <%= @event.errors.full_messages_for(:price).first %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-lg-2">
          <%= form.label :Data %><br>
        </div>
        <div class="col-lg-10">
          <%= form.date_field :date, class: "form-control" %>
          <% if !@event.errors.full_messages_for(:date).blank? %>
            <div class="alert alert-danger">
              <%= @event.errors.full_messages_for(:date).first %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-lg-2">
          <%= form.label :'Ilość miejsc' %><br>
        </div>
        <div class="col-lg-10">
          <%= form.number_field :size, class: "form-control" %>
          <% if !@event.errors.full_messages_for(:size).blank? %>
            <div class="alert alert-danger">
              <%= @event.errors.full_messages_for(:size).first %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-lg-2">
          <%= form.label :'Tylko dla dorosłych' %><br>
        </div>
        <div class="col-lg-10">
          <%= form.check_box :adult_only %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-lg-2">
          <%= form.label :Zdjęcie %><br>
        </div>
        <div class="col-lg-10">
          <%= form.text_field :image, class: "form-control" %>
          <% if !@event.errors.full_messages_for(:image).blank? %>
            <div class="alert alert-danger">
              <%= @event.errors.full_messages_for(:image).first %>
            </div>
          <% end %>
        </div>
      </div>

      <p>
        <%= form.submit :Dodaj, class: "btn btn-success"%>
      </p>

  <% end %>
  </div>
</div>

app/views/events/show.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>" style="margin: auto; margin-bottom: 5px; width: 80%;">
    <%= value %>
  </div>
<% end %>
<div class="card" style="width: 80%; margin: auto;">
  <div class="card-header">
    <%=	"#{@event.name}" %>
  </div>
  <img class="card-img-top" style="width: 50%; margin: auto;" src=<%= "#{@event.image}" %>>
  <div class="card-body">
    <p class="card-text">
    <table class="table">
      <tbody>
      <tr>
        <td>Opis:</td>
        <td><%= @event.description %></td>
      </tr>
      <tr>
        <td>Data:</td>
        <td><%= @event.date %></td>
      </tr>
      <tr>
        <td>Cena biletu:</td>
        <td><%= @event.price %></td>
      </tr>
      <tr>
        <td>Wykupione miejsca</td>
        <td>
          <%= @event.tickets.count %>
        </td>
      </tr>
      <tr>
        <td>Tylko dla pełnoletnich</td>
        <td>
          <% if(@event.adult_only) %>
            <%= "tak" %>
          <% else %>
            <%= "nie" %>
          <% end %>
        </td>
      </tr>
      </tbody>
    </table>
  </div>
</div>

<% if session[:admin] %>
  <%= render "events/tickets_list", tickets: Ticket.where(event_id: @event.id) %>
<% end %>