config/routes.rb
Rails.application.routes.draw do
  resources :tickets do
    member do
      put :do_return
      put :undo_return
      delete :submit_return
    end
    collection do
      get :to_return
    end
  end
  resources :users do
    member do
      post :add_money
      put :add_money
      put :sub_money
    end
  end
  root :to => "application#index"
  resources :events do
  end

  get 'session/login'
  get 'session/logout'
  post 'session/login_attempt'
  get 'users/tickets'

end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :event, class_name: 'Event'
  belongs_to :user, class_name: 'User'
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy, :do_return, :undo_return, :submit_return]
  before_action :check_preconditions, only: [:create]

  def check_preconditions
    if ticket_params[:amount].to_f < 0
      respond_to do |format|
        flash[:danger] = 'Musisz podać dodatnią ilość biletów do zakupu'
        format.html { redirect_to events_path }
        format.json { render root_path }
      end
    end
    $user = User.find(ticket_params[:user_id])
    $event = Event.find(ticket_params[:event_id])
    if $event[:adult_only] && ((Date.today - $user.birth) / 365).floor < 18
      respond_to do |format|
        flash[:danger] = 'Musisz być pełnoletni aby kupić bilety na to wydarzenie'
        format.html { redirect_to events_path }
        format.json { render root_path }
      end
    elsif $user[:money].to_f < ticket_params[:amount].to_f * ticket_params[:price].to_f
      respond_to do |format|
        flash[:danger] = 'Nie masz wystarczających środków na koncie'
        format.html { redirect_to events_path }
        format.json { render root_path }
      end
    elsif Ticket.where(user_id: ticket_params[:user_id], event_id: ticket_params[:event_id]).count() + ticket_params[:amount].to_f > 5
      respond_to do |format|
        flash[:danger] = 'Nie możesz kupić tylu biletów na to wydarzenie'
        format.html { redirect_to events_path }
        format.json { render root_path }
      end
    elsif $event[:size] < ticket_params[:amount].to_f + Ticket.where(event_id: ticket_params[:event_id]).count()
      respond_to do |format|
        flash[:danger] = 'Na podane wyrażenie nie ma już tylu dostępnych miejsc'
        format.html { redirect_to events_path }
        format.json { render root_path }
      end
    end
  end

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.where(user_id: session[:user_id])
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    $amount = ticket_params[:amount].to_f
    $i = 0
    @tickets = []
    while $i < $amount
      @tickets.push(Ticket.new(ticket_params.tap{|ticket_params| ticket_params.delete(:amount)}))
      $i += 1
    end
    respond_to do |format|
      if @tickets.each(&:save)
        @user = User.find(ticket_params[:user_id])
        @user.money -= $amount * ticket_params[:price].to_f
        @user.update(money: @user.money)
        flash[:success] = 'Zakupiono bilety'
        format.html { redirect_to events_path }
        format.json { render root_path }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  def do_return
    respond_to do |format|
      if @ticket.update(to_return: count_return)
        format.html { redirect_to tickets_path, class: "btn-lg btn-secondary", tickets: Ticket.where(user_id: session[:user_id]) }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  def undo_return
    respond_to do |format|
      if @ticket.update(to_return: 0)
        format.html { redirect_to tickets_path, class: "btn-lg btn-secondary", tickets: Ticket.where(user_id: session[:user_id]) }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  def to_return
    @tickets = Ticket.where("to_return > ?", 0.0)
  end

  def submit_return
    @user = User.find(@ticket.user_id)
    $temp = @ticket.to_return
    @ticket.destroy
    respond_to do |format|
      @user.update(money: @user.money + @ticket.to_return)
      flash[:success] = "Zatwierdzono zwrot"
      format.html { redirect_to to_return_tickets_path }
      format.json { head :no_content }
    end
  end
  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:price, :event_id, :user_id, :amount, :to_return)
    end

    def count_return
      return @ticket.price - (@ticket.price * 0.1) - ((1 - (@ticket.event.date - Date.today) / 30) * @ticket.price / 2)
    end

  # def person_params
  #   params.require(:ticket).permit(:name, :age)
  # end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_with(model: ticket, local: true) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :ticket_price %>
  </div>

  <div class="field">
    <%= form.label :event_id %>
    <%= form.text_field :event_id, id: :ticket_event_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :ticket_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<div style="width: 80%; margin: auto; background-color: white; border-radius: 5px;">
  <h5>Twoje bilety:</h5>
  <hr>

  <table class="table table-bordered">

    <thead>

      <tr>
        <th>Cena</th>
        <th>Data wydarzenia</th>
        <th>Wydarzenie</th>
        <th>Zwrot</th>
      </tr>
    </thead>

    <tbody>
      <% @tickets.each do |ticket| %>
        <tr>
          <td><%= ticket.price %></td>
          <td><%= ticket.event.date %></td>
          <td>
            <%= link_to ticket.event.name, event_path(ticket.event), style: "display: inline" %>
          </td>
          <td>
            <% if ticket.to_return != 0 %>
              <%= button_to 'Cofnij zwrot', undo_return_ticket_path(id: ticket.id), :method => :put, class: "btn btn-info" %>
            <% else %>
              <%= button_to 'Zwróć', do_return_ticket_path(id: ticket.id), :method => :put, class: "btn btn-info" %>
          <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tickets/new.html.erb
<div class="card" style="width: 100%;">
  <div class="card-body">
    <h5 class="card-title">Wpisz ile biletów chcesz kupic (maksymalnie 5):</h5>
    <hr>

    <%= form_with scope: :ticket, url: tickets_path, local: true do |form| %>

      <div class="form-group row">
        <div class="col-lg-2">
          <%= form.label :Ilość %><br>
        </div>
        <div class="col-lg-10">
          <%= form.text_field :amount, class: "form-control" %>
        </div>
      </div>
      <p>
        <%= form.submit :Kup, class: "btn btn-success" %>
      </p>
    <% end %>
  </div>
</div>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @ticket.price %>
</p>

<p>
  <strong>Event:</strong>
  <%= @ticket.event %>
</p>

<p>
  <strong>User:</strong>
  <%= @ticket.user %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/to_return.html.erb
<p id="notice"><%= notice %></p>
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>" style="margin: auto; margin-bottom: 5px; width: 80%;">
    <%= value %>
  </div>
<% end %>
<div style="width: 80%; margin: auto; background-color: white; border-radius: 5px;">
  <h5>Bilety do zwrotu:</h5>
  <hr>

  <table class="table table-bordered">

    <thead>

    <tr>
      <th>Cena</th>
      <th>Data wydarzenia</th>
      <th>Wydarzenie</th>
      <th>Użytkownik</th>
      <th>Zwrot</th>
    </tr>
    </thead>

    <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.price %></td>
        <td><%= ticket.event.date %></td>
        <td>
          <%= link_to ticket.event.name, event_path(ticket.event), style: "display: inline" %>
        </td>
        <td><%= ticket.user.name %></td>
        <td>
          <% if ticket.to_return != 0 %>
            <%= button_to('Zatwierdź zwrot', submit_return_ticket_path(id: ticket.id), :method => :delete, class: "btn btn-info") %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>