config/routes.rb
Rails.application.routes.draw do
  resources :tickets do
    member do
      put :do_return
      put :undo_return
      delete :submit_return
    end
    collection do
      get :to_return
    end
  end
  resources :users do
    member do
      post :add_money
      put :add_money
      put :sub_money
    end
  end
  root :to => "application#index"
  resources :events do
  end

  get 'session/login'
  get 'session/logout'
  post 'session/login_attempt'
  get 'users/tickets'

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="/" style="margin-left: 10%">Bilecik</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
          aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <% if(session[:user_id]) %>
    <p class="nav navbar-nav navbar-right" id="Logowanie" style="margin-left: 1%">
      <%= link_to 'Wyloguj', session_logout_path, class: "btn-lg btn-secondary" %>
    </p>
    <p class="nav navbar-nav navbar-right" id="Logowanie" style="margin-left: 1%">
      <%= link_to 'Doładuj konto', edit_user_path(session[:user_id]), class: "btn-lg btn-secondary" %>
    </p>
    <p class="nav navbar-nav navbar-right" id="Logowanie" style="margin-left: 1%">
      <%= link_to 'Moje bilety', tickets_path, class: "btn-lg btn-secondary" %>
    </p>
    <div class="cell-row" style="margin-left: 1%">
      <div class="cell cell-middle" style="color: white; text-align: right">
        Jesteś zalogowany jako <%= User.find(session[:user_id])[:name] %>, stan konta: <%= User.find(session[:user_id])[:money] %>
      </div>
    </div>
<% else %>
    <p class="nav navbar-nav navbar-right" id="Rejestracja" style="margin-left: 1%">
      <%= link_to 'Rejestracja', new_user_path, class: "btn-lg btn-secondary" %>
    </p>
    <p class="nav navbar-nav navbar-right" id="Logowanie" style="margin-left: 1%">
      <%= link_to 'Logowanie', session_login_path, class: "btn-lg btn-secondary" %>
    </p>
  <% end %>
  <% if session[:admin] %>
    <p class="nav navbar-nav navbar-right" id="Zwroty" style="margin-left: 1%">
      <%= link_to 'Bilety do zwrotu', to_return_tickets_path, class: "btn-lg btn-secondary" %>
    </p>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bilety</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css"
          integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">

    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">

    </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js"
            integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous">

    </script>%>
  </head>

  <body style="background-color: lightgray">
    <%= render 'layouts/navbar' %>

    <div class="main" style="margin-top: 60px">
      <%= yield %>
    </div>
  </body>
</html>/